url: https://th0r0nd0r.github.io/
baseurl: /

# Site settings
title: Parker Fritch
email: pjfritch1@gmail.com
description: "Bay Area software engineer working with Ruby on Rails, React, React Native, Redux, JavaSCript, HTML, CSS, SQL, PostgreSQL, git, jQuery, Google Maps API, and more"


# Team names, titles and social links
people:
- name: Parker Fritch
  pic: 1
  position: Coding Man
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/parker-fritch-a29b14143/
    - title: github
      url: https://github.com/th0r0nd0r

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/parker-fritch-a29b14143/
  - title: github
    url: https://github.com/th0r0nd0r

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
