url: https://th0r0nd0r.github.io/
baseurl: /

# Site settings
title: Parker Fritch
email: pjfritch1@gmail.com
description: "Bay Area software engineer working with ruby on rails, React, React Native, Redux, JavaSCript, HTML, CSS, SQL, PostgreSQL, git, jQuery, Google Maps API, and more"


# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/parker-fritch-a29b14143/
  - title: github
    url: https://github.com/th0r0nd0r

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
